### ISSUE TITLE
In php 5.6.* doesn't work

### ISSUE THREAD

**Issue by antonellomangone** [hieblmedia/simple-php-encrypter-decrypter#1]
In php 5.6.19 the library doesn't work ... when is necessary to encode, return an empty string.

**Comment by hieblmedia** [comment]
Fixed: https://github.com/hieblmedia/simple-php-encrypter-decrypter/commit/5bbd521daa941a0180810f8ee7f2a420f0265a36

Note:
Added HieblMedia in Namespace to avoid name conflicts and for use psr-4 autoload.
You must call \HieblMedia\Encryption\Encrypter for now.

**Comment by antonellomangone** [comment]
Now, it works, but it doesn't give back the same encoded strings as in the previous version, so I'll have to modify the old passwords ?
